apiVersion : apps/v1
kind: Deployment
metadata:
  name: "powegroup-770d"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "powegroup-770d"
  template:
    metadata:
      labels:
        app: "powegroup-770d"
    spec:
      containers:
        - name: "powegroup-770d"
          image: "fisionbot.azurecr.io/powegroup"
          ports:
          - containerPort: 80