apiVersion: v1
kind: Service
metadata:
    name: "amolia-59b2"
    labels:
        app: "amolia-59b2"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "amolia-59b2"