apiVersion: v1
kind: Service
metadata:
    name: "amola-a49c"
    labels:
        app: "amola-a49c"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "amola-a49c"