apiVersion: v1
kind: Service
metadata:
    name: "powegroup-734d"
    labels:
        app: "powegroup-734d"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "powegroup-734d"