on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n Limonia -g Limoniaadd1-rg --location "UK West" --sku Premium --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n Limonia --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n Limonia --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n Limonia --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: limonia.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t limonia.azurecr.io/lomania:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push limonia.azurecr.io/lomania:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_lomania_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep lomaniaa127 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace lomaniaa127`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: lomaniaa127
        container-registry-url: limonia.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: lomaniadockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: lomaniaa127
        manifests: |
          manifests/deployment-5.yml
          manifests/service-5.yml
        images: |
          limonia.azurecr.io/lomania:${{ github.sha }}
        imagepullsecrets: |
          lomaniadockerauth   
