on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n sandisa -g sandisa9a6d-rg --location "East US" --sku Premium --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n sandisa --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n sandisa --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n sandisa --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: sandisa.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t sandisa.azurecr.io/amola:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push sandisa.azurecr.io/amola:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_amola_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep amola91f7 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace amola91f7`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: amola91f7
        container-registry-url: sandisa.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: amoladockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: amola91f7
        manifests: |
          manifests/deployment-4.yml
          manifests/service-4.yml
        images: |
          sandisa.azurecr.io/amola:${{ github.sha }}
        imagepullsecrets: |
          amoladockerauth   
